### ISSUE TITLE
Polskie Marki 2.0

### ISSUE THREAD

**Issue by ad-m** [KlubJagiellonski/pola-backend#11]
Duplikat https://wspieram.to/projekt/5419/polskie-marki-20-aplikacja-dla-swiadomych-konsumentow

**Comment by jakublipinski** [comment]
great minds think alike

**Comment by ad-m** [comment]
Why it is closed?

2015-11-07 22:20 GMT+01:00 Jakub Lipinski <notifications@github.com>:

**Comment by jakublipinski** [comment]
Mógłbyś nam pomóc skonfigurować gunicorn'a? https://github.com/KlubJagiellonski/pola-backend/blob/master/Procfile
