### ISSUE TITLE
Gunicorn

### ISSUE THREAD

**Issue by ad-m** [KlubJagiellonski/pola-backend#12]
@jakublipinski , a co nie działa, że mi pokazujesz swój Procfile?

**Comment by jakublipinski** [comment]
Teraz wszystko działa. Od jutra jednak spodziewamy się trochę większego ruchu. Moje pytanie: czy nasz Procfile jest poprawny? Czy nie powinniśmy mieć więcej workerów? Czy jeśli niektóre z naszych request'ów zajmują dłużej (upload pliku i wysłanie go na Amazona), to czy wtedy żaden inny request nie jest procesowany? Jesteśmy otwarci na wszelki rady od specjalisty :)

**Comment by ad-m** [comment]
Warto pamiętać, że macie ```nginx``` na przodzie. On zajmuje się bufforowaniem i lekkim kolejkowaniem. 

Dodatkowo przy Heroku macie tzw. ```Dyno``` czyli jakby osobną instancje całego serwera, pomiędzy którymi Heroku przełącza transparentnie. Nie wiem ile macie ```Dyno``` skonfigurowanych. Nimi będzie Wam łatwo się skalować, o ile nikt nie ustawia serwera z consoli, tylko wszystko się dzieje w taki sposób, że ```git push``` wszystko ustawia.

```Dyno``` istnieją różne rodzaje ( https://devcenter.heroku.com/articles/dyno-types ). Nie wiem co skonfigurowaliście. To pod tym względem powinniście konfigurować liczbę workerów.  Przez uruchamianie dodatkowych ```Dyno``` możecie się skalować horyzontalnie ( https://devcenter.heroku.com/articles/scaling ).

Liczbę workerów - w mojej ocenie - warto ustawiać przez zmienną środowiskową ```WEB_CONCURRENCY``` niż aktualizować kod. Zapewnia to obecny kod. Nie znam Waszej konfiguracji.

Ja myślę, że skalowalność to sprawa, którą trudno z góry oceniać. Można się wpakować w koszta, które nijak się mają do zapotrzebowania. 

Ja jutro mam dzień wolny. Po prostu monitoruj w new rewlic i odezwij się jakby się coś działo. Pomyślimy czy są zasoby CPU na nowe workery, jeżeli tak to uruchomimy ich więcej. Jeżeli nie ma - będziemy myśleć dalej.

**Comment by jakublipinski** [comment]
Dzięki wielkie. Jak na razie działa super sprawnie.

**Comment by ad-m** [comment]
Można zamknąć? :smiley_cat:

**Comment by jakublipinski** [comment]
Tak, dzięki
