### ISSUE TITLE
Badania na zwięrzętach

### ISSUE THREAD

**Issue by ad-m** [KlubJagiellonski/pola-backend#13]
W odpowiedzi z API nie ma informacji czy dana firma bada swoje produkty na zwierzętach.

**Comment by jakublipinski** [comment]
Chciałbym wiedzieć jak dotrzeć do takiej informacji. I jakie inne informacje mogą interesować użytkowników...

**Comment by ad-m** [comment]
A pytaliście NGO-sy, które takie dane mogą mieć? Greenpeace itd.?
