### ISSUE TITLE
Rozszerzony opis firmy

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-backend#1363]
Chcielibyśmy, aby firma miła możliwość rozszerzenia opisu firmy. Oprócz tekstu mógłby się tam znajdować również logotyp, link do strony producenta i logotypy marek firmy.

Należałoby dodać w CMS pole „Rozszerzony opis firmy” i tam możliwość dodawania logotypu oraz linku do strony. Logotyp powinien być hiperłączem. Po kliknięciu w logo przenosi nas na stronę firmy.

Dodatkowo należałoby wprowadzić możliwość dodawania logotypów do marek firmy. Mamy już opcję dodawania marek firmy, trzeba tylko dodać opcję wstawiania logotypów i linków przekierowujących. Tutaj również logo powinno być przekierowaniem do strony konkretnek marki.

Wizualizacja:

![image](https://github.com/KlubJagiellonski/pola-backend/assets/52166969/7a1da4aa-a1fa-4ab3-b320-68e1000fd223)

**Comment by MatPerowicz** [comment]
@mik-laj @rodkiewicz @AdamWalkowski Prośba o nadanie temu priorytetu. Potrzebujemy tego zarówno w aplikacji, jaki i w wyszukiwarce na stronie głównej.

**Comment by rodkiewicz** [comment]
Propozcyja implementacji @mik-laj daj znac co sądzisz

**Comment by MatPerowicz** [comment]
Mega dzięki @rodkiewicz!

**Comment by MatPerowicz** [comment]
@mik-laj możesz na to spojrzeć 🙂?

**Comment by MatPerowicz** [comment]
@mik-laj próbuję dodać logotyp i link
![image](https://github.com/KlubJagiellonski/pola-backend/assets/52166969/c8ca7b53-c1b6-4376-851b-d517e894c1ae)

pojawia się taki błąd
![image](https://github.com/KlubJagiellonski/pola-backend/assets/52166969/e28b33cb-793b-4d34-ad48-8480a02a6247)

Prośba o sprawdzenie dlaczego to może nie działać.

**Comment by MatPerowicz** [comment]
Udało się dodać link. Błąd powoduje dodanie grafik.

**Comment by MatPerowicz** [comment]
@mik-laj daj proszę znać czy to już działa :)

**Comment by WezSieTato** [comment]
Na moje API nie wygląda tak jak powinno. Z tego co zrozumiałem potrzebujemy listy obiektów, które mają URL loga, URL strony, nazwa (przyda się dla VoiceOver).
Aktualnie zwracamy to na dwa różne sposoby:
 Dla kodu https://www.pola-app.pl/a/v4/get_by_code?code=9771644705002&device_id=%220%22 zwracamy official_url i  logotype_url zagnieżdzone razem z innymi informacjami o firmie.

Dla kodu https://www.pola-app.pl/a/v4/get_by_code?code=5900820002206&device_id=0 jest cała lista obiektów name i logotype_url na poziomie roota

Według mnie to powinno zawsze przychodzić w liście na poziomie informacji o firmie. A obiekt najlepiej jakby wyglądał tak:
```
{
 "name" : "Klub Jagielloński",
"website_url": "https://klubjagiellonski.pl/",
"logotype_url": "https://kj-pola-app-company-logotype.s3.amazonaws.com/logo/2023/12/17/KJ_ksiega_05__Logo_podstawowe_4.png"
}
```
Wszystkie pola wymagane. Jak jakiegoś brakuje to obiekt nie przychodzi.

**Comment by MatPerowicz** [comment]
@mik-laj prośba o dodanie możliwości załączenia logotypów i linków przekierowujących do marek danej firmy oto przykład:

![image](https://github.com/KlubJagiellonski/pola-backend/assets/52166969/7e5f9254-010f-479a-913b-8b95e0f59c81)
![image](https://github.com/KlubJagiellonski/pola-backend/assets/52166969/cb97d299-bd30-48ce-9a41-176099f58608)

**Comment by WezSieTato** [comment]
Zadanie zamykam. Rozszerzony opis jest już zaimplementowany. Dodatkowe zmiany, które przydałoby się dodać opisałem tu:
https://github.com/KlubJagiellonski/pola-backend/issues/3820
https://github.com/KlubJagiellonski/pola-backend/issues/3821
