### ISSUE TITLE
Podmiana logotypów

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-backend#140]
Na [tej](https://github.com/KlubJagiellonski/pola-backend/blob/master/pola/templates/index.html) stronie podmieniamy logotypy Klubu Jagiellońskiego (logo_kj.png) i Centrum Analiz Klubu Jagiellońskiego (logo_cakj.png).
![KJ_logo](https://user-images.githubusercontent.com/52166969/86642510-3e784080-bfdc-11ea-9a08-0f1b0cd47dd7.png)
![KJ_logo_CAKJ](https://user-images.githubusercontent.com/52166969/86642525-41733100-bfdc-11ea-9947-d57260034fc1.png)

**Comment by mik-laj** [comment]
Done
