### ISSUE TITLE
Ucinanie FAQ w wersji mobilnej strony pola-app.pl

### ISSUE THREAD

**Issue by bpaszcza** [KlubJagiellonski/pola-backend#150]
Odpowiedź na pytanie "Reprezentuję producenta..." przy wyświetlaniu strony pola-app.pl na telefonie jest ucięta i nie widać linka do formularza. 
![Screenshot_20200730_170121_com android chrome](https://user-images.githubusercontent.com/12826726/89315002-9e651400-d67a-11ea-94d1-a7e5890f6a0a.jpg)

**Comment by lukaszstanczak** [comment]
Cześć, sprawdziłem na wersji mobilnej i błąd nie występuje. Na jakim urządzeniu lub rozdzielczości znalazłeś błąd?

**Comment by mik-laj** [comment]
@lukaszstanczak przy szerokości ekranu 499 px ten problem występuje. 
![Uploading Screenshot 2020-10-24 at 14.23.51.png…]()

**Comment by mik-laj** [comment]
To będzie zadresowane przez nową wersje pola-web. Spójrz: https://github.com/KlubJagiellonski/pola-web
