### ISSUE TITLE
Możliwość wyświetlania marek konkretnej firmy

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-backend#1688]
Dobrze by było mieć możliwość zaznaczenia, dla której firmy wyświetlać należące do niej marki. 

Do już istniejącego, lecz ukrytego rozwiązania https://github.com/KlubJagiellonski/pola-backend/issues/671 dodajemy opcję wyboru dla których firm na się to wyświetlać.

![image](https://user-images.githubusercontent.com/52166969/159777190-332e4882-f775-4569-9aaa-990328df06be.png)

Po zaznaczeniu pola przypisane do firmy marki będą wyświetlane w opisie

![image](https://user-images.githubusercontent.com/52166969/159777331-0b358a38-49b1-4283-b9fd-21f76d8e2386.png)

**Comment by mik-laj** [comment]
Done: https://github.com/KlubJagiellonski/pola-backend/pull/1710

**Comment by mik-laj** [comment]
Edycja jest z widoku edycji firmy.
