### ISSUE TITLE
Zmiana serwerodawcy

### ISSUE THREAD

**Issue by ad-m** [KlubJagiellonski/pola-backend#17]
Szanowni,

Migrujemy do mydevil.net? Jestem z nich zadowolony. Dostrzegam ból związany z wysokimi kosztami Heroku. Wspierają hostowanie aplikacji Python, a jednocześnie wszystkimi pracami sysadminia się zajmują. Oferują m. in.redisa, postgres i django. Musielibyście sobie tylko skonfigurować np. fabrica do deploymentu, albo hook gita tzw. "git push to deploy", bo nie ma mają out-of-the-box takich takich rozwiazań jak heroku w tym zakresie.

Na wszelki wypadek daje reflink:  http://www.mydevil.net/pp/B2TSQR2WUD bo dostaniecie 20% zniżki. Dodatkowo wrzucają na mirko kody zniżkowe ( http://www.wykop.pl/ludzie/MyDevil/ ), gdzie można ich wyrwać jeszcze taniej.

Z wyrazami szacunku,

**Comment by jakublipinski** [comment]
Dzięki. Rozważamy również Digial Ocean. Dużo taniej i całkiem dobre opinie. Wiesz coś o nich?

**Comment by ad-m** [comment]
Są całkiem spoko technicznie, ale musisz mieć kogoś od administracji
serwerem, bo to jeszcze mniej niż mydevilnet. Nie ogarniają polskich
przepisów o ochronie danych osobowyvh

Wysłano z urządzenia mobilnego.
2 gru 2015 5:14 PM "Jakub Lipinski" <notifications@github.com> napisał(a):

**Comment by ad-m** [comment]
OVH już ogarnia polskie przepisy…

**Comment by jakublipinski** [comment]
Dajemy radę z Heroku, mimo wysokich cen. Wygoda jest jednak nieoceniona.
