### ISSUE TITLE
Powrót do przycisku zbiórki

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-backend#1726]
15 kwietnia zmienimy przycisk na ekranie głównym. Wracamy do promowania bezpośrednio zbiórki.

Napis: Potrzebujemy 1 zł
Link: https://klubjagiellonski.pl/zbiorka/wspieraj-aplikacje-pola/

**Comment by MatPerowicz** [comment]
@mik-laj stworzyłem Pull request https://github.com/KlubJagiellonski/pola-backend/pull/1728

**Comment by mik-laj** [comment]
Done.
