### ISSUE TITLE
bdsklep.pl - dostawcą kodów EAN

### ISSUE THREAD

**Issue by ad-m** [KlubJagiellonski/pola-backend#18]
Hej,

bdsklep.pl ma kody EAN dla produktów i ewidencjonuje dane o producencie. Może wejdą w kooperatywę?

Z wyrazami szacunku,

**Comment by jakublipinski** [comment]
Hej, mamy te dane z Instytutu Logistyki i Magazynowania - jednostki która te kody w Polsce rozdziela. Nie da się mieć lepszego dostępu :)
