### ISSUE TITLE
Zmiana przycisku zbiórki

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-backend#2224]
Pomimo zmian w pliku, w aplikacji nadal wyświetla się stary napis. Prośba o jak najszybszą zmianę tego.

https://github.com/KlubJagiellonski/pola-backend/blob/a6ec929eabf6a57edc4aaceeb17c878b02c8df85/pola/constants.py

Napis: "Wspieraj aplikację Pola"
Link: https://klubjagiellonski.pl/zbiorka/wspieraj-aplikacje-pola/

![image](https://user-images.githubusercontent.com/52166969/195045802-f69364f1-8c1d-4faa-a73c-1c4b12c8ccdb.png)

**Comment by skica-dev** [comment]
rerun CI Build #4910

**Comment by MatPerowicz** [comment]
@skica-dev @mik-laj nadal wyświetla się stary napis. Kiedy będzie się wyświetlał właściwy?
