### ISSUE TITLE
Nie mogę zbudować lokalnie strony https://www.pola-app.pl/ na branchu z mastera.

### ISSUE THREAD

**Issue by lukaszstanczak** [KlubJagiellonski/pola-backend#277]
Cześć,

Pobrałem kod z repozytorium pola-web, zainstalowałem odpowiednie komponenty, zbudowałem projekt i uruchomiłem na localhost:3000. Strona która pokazała mi się w przeglądarce przypomina początkowy projekt w react.js. W kodzie źródłowym też nie zauważyłem kodu odpowiedniego dla strony https://www.pola-app.pl/. Czy kod właściwy strony jest na jakimś innym branchu, do którego nie mam dostępu? Może pominąłem jakiś krok w budowaniu projektu i dlatego widzę tylko stronę startową reacta?

Pozdrawiam,
Łukasz

**Comment by mik-laj** [comment]
My w tym projekcie jeszcze nie używamy React. Mamy za to dokumentacje, która opisuje, jak ruuchomić cześć Django: 
https://github.com/KlubJagiellonski/pola-backend#uruchamianie-aplikacji
Jeśli chodzi o frontend to on może być w cięższym stanie psychicznym, ale planowane jest jego przepisanie wkrótce, wiec osobiście bym nie inwestował w to czas. Tylko Docker na razie jest potrzebny. 

Aplikacja Reacta jest na razie niezależna i nie została jeszcze scalona: 
https://github.com/KlubJagiellonski/pola-web

**Comment by mik-laj** [comment]
Hej. Czy potrzebujesz. pomocy?

**Comment by lukaszstanczak** [comment]
Hej,

Dzięki za odpowiedź. Znalazłem plik `.env.example`. Widzę że jest wypełniony domyślnymi danymi. Jakie dane mi są potrzebne żeby stworzyć prawidłowy plik `.env`?

**Comment by mik-laj** [comment]
> Jakie dane mi są potrzebne żeby stworzyć prawidłowy plik .env?

Prawdopodobnie już żadnymi. Wiele integracji my porzuciliśmy, ale jeszcze w kodzie nie zostało to uprzątnięte. Dla prostych celów deweloperskich po prostu wystarczy skopiować ten plik i nie przejmować się jego zawartością.
