### ISSUE TITLE
Nowa strona zbiórki

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-backend#3602]
@mik-laj strona zbiórki w lutym nie działała poprawnie przeszliśmy z T-pay na PayU i mamy teraz nową stronę.

Prośba o zmianę przycisku zbiórki:
Tekst: **Twój 1 zł może nam pomóc!**
Link: https://klubjagiellonski.pl/zbiorka/wspieraj-aplikacje-pola/

**Comment by MatPerowicz** [comment]
Próbuję to zmienić @mik-laj 

https://github.com/KlubJagiellonski/pola-backend/pull/3604

**Comment by MatPerowicz** [comment]
Próbowałem to zmienić: 
https://github.com/KlubJagiellonski/pola-backend/pull/3604

**Comment by MatPerowicz** [comment]
Pojawia się taki błąd
![image](https://github.com/KlubJagiellonski/pola-backend/assets/52166969/5ce411bf-55e1-4eec-8096-e169468d4b6f)

**Comment by MatPerowicz** [comment]
Błąd można zobaczyć tutaj:
https://github.com/KlubJagiellonski/pola-backend

![image](https://github.com/KlubJagiellonski/pola-backend/assets/52166969/c6665085-9b60-447b-a955-880c4b6d08df)

**Comment by MatPerowicz** [comment]
Proponowane rozwiązania:

1. Przestarzała konfiguracja: Otrzymałeś ostrzeżenia dotyczące przestarzałych nazw konfiguracji w dbt_project.yml. source-paths powinno zostać zmienione na model-paths, a data-paths na seed-paths. Należy zaktualizować plik konfiguracyjny, aby uniknąć przyszłych ostrzeżeń i potencjalnych błędów.

2. Zalecenia dotyczące ekspozycji: W wersji dbt 1.3 i nowszych, nazwa ekspozycji (name w konfiguracji ekspozycji) powinna zawierać tylko litery, cyfry i podkreślniki. Zaleca się użycie nowej właściwości label dla bardziej przyjaznych tytułów, które mogą zawierać spacje, wielkie litery i znaki specjalne. Należy zaktualizować konfiguracje, aby uniknąć przyszłych błędów.

3. Błąd połączenia z bazą danych: Podczas próby wykonania poleceń dbt, wystąpił błąd związany z połączeniem do serwera bazy danych (timeout). Oznacza to, że dbt nie może nawiązać połączenia z bazą danych z powodu przekroczenia limitu czasu. Może to być spowodowane problemami z siecią, niewłaściwą konfiguracją dbt (np. błędne dane uwierzytelniające), lub serwerem bazy danych, który nie jest dostępny.

**Comment by scudetto1994** [comment]
Mat, sprawdź, czy usługa postgres w services.msc działa.

**Comment by MatPerowicz** [comment]
Obecny problem polega też na tym, że nie mamy osoby, która mogłaby na to spojrzeć :(

**Comment by DjWarmonger** [comment]
Zmieniłeś adres strony. Czy ta baza też chodzi na serwerze o tym adresie?

**Comment by MatPerowicz** [comment]
@DjWarmonger W lutym przycisk kierował do tej strony https://klubjagiellonski.pl/zbiorka/wspieraj-aplikacje-pola/

4 marca zmieliliśmy to i zaczęliśmy linkować do tej strony: https://www.pola-app.pl/1-5-podatku-na-aplikacje-pola

Teraz chcemy wrócić do linkowania strony: https://klubjagiellonski.pl/zbiorka/wspieraj-aplikacje-pola/

Tej samej co wcześniej.

Baza i strona, do której chcemy linkować, nie są na tym samym serwerze, ale już wcześniej linkowaliśmy do tej strony i to działało.

Chętnie odpowiem na wszystkie pytania.

**Comment by MatPerowicz** [comment]
Komentarz z Twittera „Pisze Database Error -- problem z połączeniem, ale raczej z serwerem bazodanowym. Po co baza danych w buildowaniu? Do testów? Potrzebna diagnoza DevOps”

**Comment by tmotyl** [comment]
Co ciekawe buildy są czerwone od stycznia, z małymi wyjątkami. 
Czym sie te buildy różnią? Przykład z jednego dnia:

zielony: https://github.com/KlubJagiellonski/pola-backend/actions/runs/8165595190/job/22323138750


czerwony: 
https://github.com/KlubJagiellonski/pola-backend/actions/runs/8167133614/job/22327202841

Różnica jest w jobie "Set environment env variable"
gdzy przechodzi to jest:
```
Deploy BI (push) - refs/heads/prod
Run source <(python ./pola-bi/dbt/dev.py --environment prod)
```
a gdy nie przechodzi to jest:
```
Deploy BI (push) - refs/heads/master
Run source <(python ./pola-bi/dbt/dev.py --environment staging)
```

zgodnie z kodem w ci.yaml:
```
  deploy-bi:
    name: "Deploy BI (push) - ${{ github.ref }}"
    runs-on: ubuntu-latest
    needs: [prod-image, bi-validate]
    if: >-
      github.event_name == 'push' &&
      (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/prod')
```
wiec wygląda na to, ze bild przechodzi tylko jesli jest budowany z gałęzi "prod"

**Comment by camaeel** [comment]
Jesli to jest deployment to strzelam ze runner nie ma dostepu sieciowego do tej bazy. Pewnie firewall nie jest otwarty. 

@tmotyl Zmiana linku platnosci to niekoniecznie tylko zmiana linku, a czesto nietrywialne integracje z partnerem (nie przegladalem PRa to nie wiem).

**Comment by pwilkin** [comment]
Przepchnięte na prod, do problemów z bazą staging otwieram https://github.com/KlubJagiellonski/pola-backend/issues/3624

**Comment by tmotyl** [comment]
> @tmotyl Zmiana linku platnosci to niekoniecznie tylko zmiana linku, a czesto nietrywialne integracje z partnerem (nie przegladalem PRa to nie wiem).

Zgadza sie, zwykle tak jest. W tym przypadku jednak chodzi o link.
