### ISSUE TITLE
Prostsze rozpatrywanie wszystkich zgłoszeń dotyczących danego kodu

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-backend#368]
Obecnie przy rozpatrywaniu zgłoszenia nie da się rozpatrzyć wszystkich innych zgłoszeń dla tego produktu. Trzeba otworzyć inną kartę i tam skorzystać z tej możliwości.

Czy opcja "rozpatrz wszystkie zgłoszenia" może być dostępna w tym ekranie? 

![image](https://user-images.githubusercontent.com/52166969/104562482-b5a42680-5648-11eb-8d9b-33166c0629fd.png)

**Comment by mik-laj** [comment]
@rodkiewicz

**Comment by rodkiewicz** [comment]
Zajmę się tym w wolnej chwili, prawdopodobnie w tym tygodniu.

**Comment by MatPerowicz** [comment]
Super, dzięki 🙂

pon., 1 mar 2021, 17:29 użytkownik Mikołaj Rodkiewicz <
notifications@github.com> napisał:

**Comment by mik-laj** [comment]
Close: #https://github.com/KlubJagiellonski/pola-backend/pull/468
