### ISSUE TITLE
Dodanie pola website_url do obiektu brand dla endpointu get_by_code

### ISSUE THREAD

**Issue by WezSieTato** [KlubJagiellonski/pola-backend#3821]
## Opis
W celu wzbogacenia informacji dostarczanych przez nasze API, wymagane jest dodanie nowego pola `website_url` do każdego obiektu brand w strukturze danych JSON. Pole to będzie zawierało URL do oficjalnej strony internetowej danej marki, co ułatwi użytkownikom uzyskanie dodatkowych informacji o marce.

## Szczegóły implementacji:

Pole `website_url`: Każdy obiekt brand w odpowiedzi JSON będzie rozszerzony o nowe pole` website_url`, które będzie przechowywało URL jako string.
Przykładowa wartość dla marki Pola:
```
{
  "name": "Pola. Zabierz ją na zakupy",
  "logotype_url": "https://kj-pola-app-company-logotype.s3.amazonaws.com/brand-logotype/2024/03/25/pola_logo_1.png",
  "website_url": "https://www.pola-app.pl"
}
```

Pole to powinno być wymagane w obiekcie brand.  Opis zmian po stronie CMS dostarczy @MatPerowicz

**Comment by cincinek** [comment]
@WezSieTato 
Dane dla `get_by_code` generowane są w metodzie `get_result_from_code` w pliku `logic.py`. W tej metodzie dane na temat marki, są tylko tworzone dane dla firm
```python
            if product_company:
                companies.append(product_company)
                result['name'] = product_company.common_name or product_company.official_name or product_company.name
            if brand_company:
                companies.append(brand_company)
```
Czy w zadaniu chodzi o to, żeby generalnie zmodyfikować `get_result_from_code`, tak aby zwracała informację na temat marki io rozbudowaniu dodać pole `website_url`do modelu brand?
Czy może coś pomieszałem i zmiany są potrzebne gdzieś indziej w kodzie?

**Comment by WezSieTato** [comment]
Nie wiem jak to jest zaimplementowane. Ja jestem tylko konsumentem tego API :) 
Mi chodzi o to, żeby brand miało dodatkowe pole. Jeśli o chodzi o zmodyfikowania struktury company, żeby zwracała informacje o markach to na to też jest zadanie #3820
