### ISSUE TITLE
Aktualizacja Django do stabilnej wersji

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-backend#39]
Używamy b. starej, niewspieranej wersji Django.

**Comment by ad-m** [comment]
Z mojego doświadczenia warto to przeprowadzić wraz z uzupełnieniem choćby części pokrycia testów automatycznych, choćby testów integracyjnych. Wówczas kolejne aktualizacje idą też przyjemniej.

**Comment by mik-laj** [comment]
W sprawie testów stworzyłem osobne zgłoszenie #46

**Comment by mik-laj** [comment]
Done via https://github.com/KlubJagiellonski/pola-backend/commit/6ec22db12e4a8020fccda67447b1b01b54a9d7c0
