### ISSUE TITLE
Marki producentów (brands) - baza danych i CMS

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-backend#40]
Chcemy wiedzieć jakie marki należą do poszczególnych producentów.

Trzeba stworzyć tabelę `company_brands` (name, company_id). Zmiany w tabeli `company_brands` powinny być rejestrowane (przez `reversion`).

Trzeba stworzyć interfejs do CMS do dodawania, edycji i usuwania marek - najprościej jako pole tekstowe multiline.
 
Lista kroków:
- [x] stworzyć encje `brands`
- [ ] stworzyć widok tworzenia, edycji, listy, kasowania
- [ ] dodać do formularza `CompanyForm` pole wprowadzania marek. Najlepiej z natychmiastowym powiadamianiem(JS) o duplikatach, ale to opcjonalne. Może być również w formie pola wielolinijkowego i walidacja po stronie serwera. 
- [x] zadbać, aby były zapisywane zmiany w rewizjach. (Najprawdopodobniej zapisując zmiany w polu JSON w `Company`)

**Comment by mik-laj** [comment]
Pewne próby były podejmowane na
https://github.com/KlubJagiellonski/pola-backend/tree/brand-and-search

**Comment by mik-laj** [comment]
Trudno z czasem i za dużo krwi mi psuje Python.
