### ISSUE TITLE
Wyszukiwarka na głównej stronie i profil firmy

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-backend#42]
Pasek wyszukiwania na głównej stronie, w którym będzie można wpisać: kod kreskowy, nazwę produktu, markę lub nazwę firmy. Wyszukiwarka ma być super-szybka i powinna dopełniać wyniki. Wyszukanie prowadzi do profilu firmy, który wyświetla te same informacje co aplikacja mobilna (i może podobnie wyglądać).

Wymaga wcześniej zrobienia #40

**Comment by mik-laj** [comment]
To też już coś było robione. Jest w branchu, który jest wspominany w #40. Dodatkowo dodane jest wyszukiwanie przez kamerę.

**Comment by mik-laj** [comment]
Tutaj warto pomyśleć, aby jakieś zrobić mockupy, czy coś z grafikiem. Może to ostatnio mnie zabiło, że mysłałem o zbyt dużej liczbie rzeczy na raz?
