### ISSUE TITLE
Możliwość zgłoszenia zmian w opisie/danych firmy

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-backend#44]
Użytkownik może zgłosić zmianę w opisie/danych firm (również w markach). Propozycja zmian rozpatrywana jest przez redakcję i może być odrzucona/częściowo zaakceptowana/całkowicie zaakceptowana.

Aby zgłosić zmianę, użytkownik musi rozwiązać np. reCaptchę. Historia zgłoszeń zmian i ew. akceptacji dostępna jest w historii zmian (#43)

Wymaga #42

**Comment by mik-laj** [comment]
Kiedyś było dyskutowane, że powinny być to zmiany in-place. Miałem problem, jak to fajnie ogarnąć w Django, ale trzeba będzie porzucić crispy i inne cuda do formularza, ale ręcznie wszystko obsłużyć. Miałem też pomysł, aby skorzystać Knockout, ale to chyba przestzał. Zrobić idzie to za pomocą jQuery.
