### ISSUE TITLE
Sitemap, og-tag'i i semantic web w profilu firmy

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-backend#45]
Mamy na stronie sitemap, który pozwala wyszukiwarką odnaleźć wszystkie profile firm.

Profile firm zawierają poprawne og-tags i tagi semantic web. 

Wymaga #42

**Comment by mik-laj** [comment]
Tutaj warto pamiętać, aby w szczególności dać 
http://schema.org/Rating
Ale ciekawe będzie też
http://schema.org/Brand
http://schema.org/Product
http://schema.org/Corporation
https://www.gs1.org/voc/ (zewnętrzny, ale ścliśle powiązany)
