### ISSUE TITLE
Nie jest możliwe dodanie produktu przez ProductCreate

### ISSUE THREAD

**Issue by mik-laj** [KlubJagiellonski/pola-backend#47]
Szanowni.

Nie jest możliwe dodanie produktu z poziomu panelu CMS, ponieważ pole `code` jest zablokowane przed edycją.
Co w związku z tym robimy? Kasujemy ten widok, czy wprowadzamy inny mechanizm?

Z wyrazami szacunku

**Comment by jakublipinski** [comment]
Dopóki redakcja nie zgłasza zapotrzebowania, proponuję schować tę opcje.
