### ISSUE TITLE
Automatyczne sprawdzanie jakości kodu

### ISSUE THREAD

**Issue by mik-laj** [KlubJagiellonski/pola-backend#50]
Szanowni,

Mamy już trochę testów, a więc jest już coś do monitorowania, aby ta aplikacja nie zestarzała się zbyt szybko. 
Proponuje uruchomienie następujących usług:
- [Travis-CI](https://travis-ci.org/) - testy automatyczne kodu.
- [CodeClimat](https://docs.codeclimate.com/v1.0/docs/travis-ci-python-test-coverage) - szukanie słabych błędów w kodzie, pomiar pokrycia testami
- [PyUp](https://pyup.io/) - automatyczne bezpieczeństwa i zależności

Z wyrazami szacunku

Ps. Wołam @ad-m aby wyraził swoje zdanie. Może on poleca inne aplikacje

**Comment by ad-m** [comment]
Tak, to racjonalny zestaw.

**Comment by jakublipinski** [comment]
Przychylam się

**Comment by mik-laj** [comment]
@jakublipinski, ja travisa nie mogę włączyć. Musisz zalogować się i włączysz.

**Comment by mik-laj** [comment]
Pyuo już działa. CodeClimat pewnie podobnie jak Travis.

**Comment by jakublipinski** [comment]
@mik-laj Travis i CodeClimat aktywowane dla pola-backend

**Comment by mik-laj** [comment]
Dzisiaj w nocy postaram się zatem ogarnąć.

**Comment by mik-laj** [comment]
Już skończone. 76 pokrycia, ale ważne, że będzie monitorowane.
