### ISSUE TITLE
SSL na Heroku

### ISSUE THREAD

**Issue by mik-laj** [KlubJagiellonski/pola-backend#55]
Szanowni,

Zauważyłem, że w Heroku wykupujemy [SSL Endpoint](https://devcenter.heroku.com/articles/ssl-endpoint), ale od marca jest wsparcie dla [Heroku SSL](https://blog.heroku.com/announcing-automated-certificate-management), czyli darmowych certyfikatów, które są automatycznie odnawiane. Należy przejść na nowy mechanizm, aby obniżyć niesieczne koszty o 20$ miesięcznie, czyli....900 zł w ciągu roku. 

Przydatne linki: 
[Migrate from SSL:Endpoint to Heroku SSL](https://devcenter.heroku.com/articles/ssl#migrate-from-ssl-endpoint-to-heroku-ssl)

Z wyrazami szacunku.

**Comment by jakublipinski** [comment]
Oh wow. Zajmę się tym asap

**Comment by jakublipinski** [comment]
Zrobione! Dzięki
