### ISSUE TITLE
Interfejs do przeglądania, usuwania i weryfikowania zdjęć do AI

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-backend#56]

**Comment by mik-laj** [comment]
Możesz powiedzieć więcej czego potrzebujesz?

**Comment by jakublipinski** [comment]
Robię to już. Ale na pewno będzie to można usprawnić np. dodając AJAX'a którego nie umiem :/

**Comment by mik-laj** [comment]
A to i tak napisanie co powinno być na tym widoku usprawni dopisanie Ajaxa. Ja go jakoś trochę umiem, a więc nie będzie problemu.

**Comment by jakublipinski** [comment]
Prosty interfejs web'owy go przeglądania zdjęć do uczenia Poli przesłanych przez użytkowników.
Redaktor może usunąć całą sekwencję, zaakceptować (OK), odrzucić (Nie OK) lub usunąć pojedyńcze zdjęcie.

**Comment by jakublipinski** [comment]
@mik-laj  Ja wiem, że to nie jest najpiękniejszy kod. Pewnie można dodać AJAX i paginację, ale ja muszę zająć się w końcu AI, więc tylko na to mnie stać w tej chwili :(

**Comment by mik-laj** [comment]
Oj to mogłeś opisać, a ja bym się zajął reszta. Spojrzę jutro na to i upiększe.

**Comment by jakublipinski** [comment]
Dzięki!
