### ISSUE TITLE
Automatyczne wyświetlanie marek przypisanych do firmy

### ISSUE THREAD

**Issue by MatPerowicz** [KlubJagiellonski/pola-backend#671]
Mamy w bazie listę marek producenta, o której użytkownik nie wie. Dlatego warto wyświetlać je automatycznie w opisie, tak jak na obrazku.

Kolor, rozmiar i styl czcionki powinien być taki sam jak w opisie. Marki powinny być wymienione od nowego wiersza (enter od opisu) i najlepiej, aby nie były zapisane caps lokiem.

![image](https://user-images.githubusercontent.com/52166969/120010021-f2abfc80-bfdc-11eb-97cd-b4593f98e9fb.png)

![image](https://user-images.githubusercontent.com/52166969/120008442-3dc51000-bfdb-11eb-8f6e-162427d6b7b4.png)

**Comment by MatPerowicz** [comment]
@mik-laj niestety musimy to cofnąć :( Wyszło na to, że ten obszar jest zupełnie nieuporządkowany w naszej bazie. Może wystarczy zrobić tak, aby to się nie wyświetlało, a jak uporządkujemy dane, to odsłonimy to z powrotem?

![pola3 — kopia](https://user-images.githubusercontent.com/52166969/145685052-8856e217-6bf0-4c7c-90fd-c88fdc62072f.PNG)
![Pola2 — kopia](https://user-images.githubusercontent.com/52166969/145685053-25b3cfa7-cf79-4286-901d-7c6390d314b8.PNG)

**Comment by mik-laj** [comment]
Tymczasowo wyłączone.
