### ISSUE TITLE
API dla Ulubione Firmy

### ISSUE THREAD

**Issue by czater** [KlubJagiellonski/pola-backend#746]
Aby zrealizować tą funkcjonalność, prawdopodobnie potrzebne będzie zwracanie jakiegoś identyfikatora dla firm, który poźniej będzie można użyć do zapisania danej firmy lokalnie i pobrania danych o tej firmie w razie potrzeby. Dyskusja na Slack: https://klubjagiellonski.slack.com/archives/C015ZM77X7U/p1623175248001500

**Comment by MatPerowicz** [comment]
Porzucona koncepcja
