### ISSUE TITLE
Dwa procesy na dyno

### ISSUE THREAD

**Issue by mik-laj** [KlubJagiellonski/pola-backend#81]
Szanowni,

Warto rozważyć obniżenie kosztów poprzez uruchomienie workera i www na jednym dyno. 
Przydatny może być w tym celu [honcho](https://honcho.readthedocs.io/en/latest/#). Wprowadzona poprawka zmniejszy koszty o 84$ (250 zł) w skali roku. 
Zobacz także: https://tartarus.org/james/diary/2013/04/18/running-statsd-on-heroku

Z wyrazami szacunku

**Comment by jakublipinski** [comment]
Prawda jest taka że tego rq workera używaliśmy tylko do debug'owego przesyłania zdjęć AI na kanał Slack'owy. Ostatnio to wyłączyłem, więc tego workera wyłączam. Dzięki za pomysł.
