### ISSUE TITLE
Dodanie możliwości grupowego dodawania kodów EAN 

### ISSUE THREAD

**Issue by BartoszZabek** [KlubJagiellonski/pola-backend#88]
Szanowni,

Bardzo dobrą i perspektywiczną opcją jest dodanie możliwości grupowego dodawania kodów EAN pod dane przedsiębiorstwo. Przykładowo, ostatnio napisała do nas firma Pol-Foods z prośbą o dodanie ich produktów. [Przesłali również plik xls,](https://drive.google.com/open?id=1vrPt1Xq7QY8olAXYEA90ga_rnRe4AS_n) w którym wyróżniono poszczególne produkty oraz ich nazwy. Firma: https://www.pola-app.pl/cms/company/48335/

**Comment by mik-laj** [comment]
Na razię robię to skryptem
````python
from company.models import Company
from product.models import Product
comp = Company.objects.get(id=XXX)

text = """UNI-BIEL Uniwersalny proszek do prania 70 g	5904284050643
UNI-BIEL Uniwersalny proszek do prania (saszetkowany) 420 g	5904284420903"""

entries = [line.split('\t') for line in lines]
entries = [entry for entry in entries if len(entry) == 2]
entries = [entry for entry in entries if not Product.objects.filter(code=entry[1]).exists()]
entries = [Product.objects.create(company=comp, name=entry[0], code=entry[1]) for entry in entries]

**Comment by mik-laj** [comment]
W podstawowej wersji, my możemy oczekiwać, że użytkownik doda dane, jako plik CSV o odpowiedniej strukturze (code, product_name) oraz będzie dodawać wpisy tylko dla jendnego produenta w danym arkuszu.

**Comment by MatPerowicz** [comment]
Wykonane
