### ISSUE TITLE
GS1 - Nowe API

### ISSUE THREAD

**Issue by mik-laj** [KlubJagiellonski/pola-backend#89]
Szanowni,

Jest nowe API REST do obśługi GS1:
http://www.produktywsieci.gs1.pl/Database
Należy sprawdzić, czy powinniśmy się zaktualizować tj. czy aktualizacja coś da, czy stare API funkcjonuje.

Z wyrazami szacunku

**Comment by mik-laj** [comment]
Powiązanym z tym zgłoszeniem mogą być problemy zgłaszane przez New Relic. 
https://rpm.newrelic.com/accounts/1105931/applications/9393343/traced_errors/a914b24a-52a8-11e8-a5bb-0242ac11000a_0_6658

**Comment by jakublipinski** [comment]
Naprawione w https://github.com/KlubJagiellonski/pola-backend/commit/c7e044f9efd73b3e7671d7f56e65d6139c41181b
