### ISSUE TITLE
Informacja zwrotna - uwagi dotyczące instalacji

### ISSUE THREAD

**Issue by virtenv** [KlubJagiellonski/pola-backend#94]
Dzień dobry,

Poniżej informacja zwrotna z procesu instalacji:

- odwiedziłem stronę https://github.com/KlubJagiellonski/pola-backend
- pobrałem źródła projektu
- zainstalowałem dla:

a) system operacyjny: GNU/Linux
b) środowisko:
- Python v. 3.7.2
- pip v. 18.1
- virtualenv v. 16.4.1
- postgres (PostgreSQL) 10.7
- ustawienia bazy danych:

   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 pola      | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres         +
           |          |          |             |             | postgres=CTc/postgres+
           |          |          |             |             | myuser=CTc/postgres

- Polecenie: "pip install -r requirements/local.txt --user"
wymusiło aktualizację w "requirements/base.txt": django-filter==2.1.0

- Polecenie: "python manage.py migrate" zwróciło:

ERRORS:
ai_pics.AIAttachment: (auth.E005) The permission codenamed 'view_aiattachment' clashes with a builtin permission for model 'ai_pics.AIAttachment'.
ai_pics.AIPics: (auth.E005) The permission codenamed 'view_aipics' clashes with a builtin permission for model 'ai_pics.AIPics'.
company.Brand: (auth.E005) The permission codenamed 'view_brand' clashes with a builtin permission for model 'company.Brand'.
company.Company: (auth.E005) The permission codenamed 'view_company' clashes with a builtin permission for model 'company.Company'.
product.Product: (auth.E005) The permission codenamed 'view_product' clashes with a builtin permission for model 'product.Product'.
report.Report: (auth.E005) The permission codenamed 'view_report' clashes with a builtin permission for model 'report.Report'.

- W związku z powyższym, w plikach "base.txt local.txt production.txt test.txt" zaktualizowałem wersje używanych modułów do najnowszych stabilnych oraz w plikach:

ai_pics/models.py:        permissions = (
ai_pics/models.py:        permissions = (
company/models.py:        permissions = (
company/models.py:        permissions = (
product/models.py:        permissions = (
report/models.py:        permissions = (

zakomentowałem permissions, czyli wiersze:

("view_aipics", "Can see all AIPics"),
("view_aiattachment", "Can see all AIAttachment"),
("view_company", "Can see all company"),
("view_brand", "Can see all brands"),
("view_product", "Can see all product"),
("view_report", "Can see all report"),

- Ponownie uruchomiłem polecenie: "python manage.py migrate", które utworzyło strukturę bazy danych, chociaż zwróciło błąd:

"psycopg2.IntegrityError: duplicate key value violates unique constraint "auth_permission_content_type_id_codename_01ab375a_uniq"
DETAIL:  Key (content_type_id, codename)=(16, view_product) already exists."

- Po utworzeniu superużytkownika, uruchomieniu serwera i zalogowaniu się na stronie http://127.0.0.1:8000/cms jako superużytkownik, otrzymałem wiadomość:

"Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: 
 =?utf-8?q?=5Bexample=2Ecom=5D_Prosz=C4=99_potwierd=C5=BA_adres_e-mail?=
From: webmaster@localhost
To: admin@domain.com
Date: Sun, 24 Feb 2019 15:40:33 -0000
Message-ID: <155102283376.10636.10142764303969378768@localhost.localdomain>

Hello from example.com!

You're receiving this e-mail because user admin has given yours as an e-mail address to connect their account.

To confirm this is correct, go to http://127.0.0.1:8000/accounts/confirm-email/MQ:1gxvtJ:j_BtfDFu6fm-ZLBFXCD5BYpkkho/

Dziekuje z example.com!
example.com:"

- Po potwierdzeniu adresu e-mail, mogłem się zalogować na stronie http://127.0.0.1:8000/cms

- Cookies zapisane w przeglądarce umożliwiły skorzystanie ze strony http://127.0.0.1:8000/admin/ bez potrzeby ponownego logowania, czyli dobrze.

- Uzyskany stan porównałem ze stronami produkcyjnymi:

https://www.pola-app.pl/cms
oraz
https://www.pola-app.pl/admin

Jeśli strona internetowa jest rozwijana, w kontekście https://github.com/KlubJagiellonski/pola-backend/issues/46 polecałbym cypress i w trybie headless wpięcie testów do pipeline, np. "npm run:cy" w celu uruchomienia: "cypress run --reporter mocha-multi-reporters --reporter-options configFile=config.json"
[base.txt](https://github.com/KlubJagiellonski/pola-backend/files/2898091/base.txt)
[local.txt](https://github.com/KlubJagiellonski/pola-backend/files/2898092/local.txt)
[production.txt](https://github.com/KlubJagiellonski/pola-backend/files/2898093/production.txt)
[test.txt](https://github.com/KlubJagiellonski/pola-backend/files/2898094/test.txt)

**Comment by mik-laj** [comment]
Hej. 

Bardzo dziękuje za podzielenie się informacji z procesu instalacji. My zmigrowaliśmy w pełni do środowiska Docker. Zaktualizowałem plik README.md. https://github.com/KlubJagiellonski/pola-backend/pull/175
Czy możesz spojrzeć, czy odpowiada on na twoje wątpliwości.

W sprawie testów, to nasza aplikacja wykorzystuje głównie widoki HTML, więc myślę, że [testy Django](https://docs.djangoproject.com/en/3.1/topics/testing/) są wystarczające.

Z wyrazami szacunku

**Comment by virtenv** [comment]
@mik-laj Dziękuję za informację zwrotną. Dobra wiadomość jest taka, że aplikację udało się zainstalować bez większych problemów i działa. Poniżej podsumowanie procesu instalacji.

Środowisko:
- najnowsza wersja docker ze Snapcraft
- docker-compose z Fedora 32

I. Po uruchomieniu sudo docker-compose up

a) ERROR: Couldn't find env file: /home/wojtek/workspace/pola-backend/pola/.env
Musiałem touch .env

b) Niespełniona zależność
debconf: delaying package configuration, since apt-utils is not installed
Tego nie poprawiałem.

c) Potem było:
"You have 71 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): account, admin, ai_pics, auth, company, contenttypes, pola, product, report, reversion, sessions, sites, socialaccount, users."

postgres_1  | LOG:  incomplete startup packet

i gdy zgodnie z opisem ruchomiłem polecenie docker-compose run web migrate a potem jeszcze dla sprawdzenia podmontowałem kontener i ponownie uruchomiłem polecenie:
root@596bfb0d65e6:/app# python manage.py migrate
Operations to perform:
  Apply all migrations: account, admin, ai_pics, auth, company, contenttypes, pola, product, report, reversion, sessions, sites, socialaccount, users
Running migrations:
  No migrations to apply.

czyli wszystko się dograło i ok.

d) Uwaga dotycząca adresu 0.0.0.0 
web_1       | Invalid HTTP_HOST header: 'localhost:8080'. You may need to add 'localhost' to ALLOWED_HOSTS.
Środowisko deweloperskie mogłoby być domyślnie konfigurowane na localhost, ale nie musi, rzecz jasna.

e) Pod adresem http://0.0.0.0:8080/cms/ai_pics/ jest napis: ,,Zdjęcia AI". Nie wiem, co to znaczy.
f) Pod adresem http://0.0.0.0:8080/accounts/confirm-email/ jest napis:
,,Zweryfikuj swój adres e-mail
We have sent an e-mail to for verification. Follow the link provided to finalize the signup process. Please contact us if you do not receive it within a few minutes."
Brak lokalizacji.

Z wyrazami szacunku

**Comment by mik-laj** [comment]
> a) ERROR: Couldn't find env file: /home/wojtek/workspace/pola-backend/pola/.env

Dodałem stosowne informacje 

> b) Niespełniona zależność

Dodałem brakujące zalezności do środowiska

> c) Potem było:

Ciesze się, zę wszystko się udało.

> d) Uwaga dotycząca adresu 0.0.0.0

Na gałezi z plikiem README.md jest ta poprawka juz wprowadzona.

> e) Pod adresem http://0.0.0.0:8080/cms/ai_pics/ jest napis: ,,Zdjęcia AI". Nie wiem, co to znaczy.

To jest nieukończony moduł. Pola miała rozpoznawać zdjęcia produktów wykorzystujac zdjęcia produktów, a nie tylko kod kreskowy, ale na razie jesteśmy na etapie zbierania danych. Niekiedy jak zeskanujesz produkt to możesz zostąc poproszony o zdjęcie produktu z kilku zdjęć, które wykorzystamy do szkolenia modelu AI

> f) Pod adresem http://0.0.0.0:8080/accounts/confirm-email/ jest napis:

Czy chciałbyś zająć się tym problemem? Ja chętnie pprzejrzę twoją zmianę. Ogólnie dla użytkownika końcowych przeznaczony jest tylko ekran główny dostępny pod https://www.pola-app.pl/ + kilka stron statycznych. Reszta widoków jest dostępna tylko dla waskiego gronaa ekspertow.

**Comment by virtenv** [comment]
@mik-laj Widzę, że sprawa localhost jest już rozwiązana.
ALLOWED_HOSTS = ['0.0.0.0', 'localhost']

Wobec tego koniec wątku.
