### ISSUE TITLE
Wersja przeglądarkowa

### ISSUE THREAD

**Issue by KarwaszTwarz** [KlubJagiellonski/pola-backend#95]
Czy istnieje wersja przeglądarkowa aplikacji Pola?

**Comment by mik-laj** [comment]
Hej. 
Niestety nie. Nie udało się nam zorganizowac chętnych, którzy chcieli by rozwijać Pole na tej platformie
Pozdrawiam.

**Comment by appsesive** [comment]
Hej, a jakby znaleźli się chętni ? Chętnie bym wziął w tym udział.

**Comment by karamucho** [comment]
Hej, również wziąłbym udział w projekcie, na wiki jest adres: http://pola.tracz.org.pl/, ale strona nie działa, mogę odświeżyć projekt, tylko jak się do tego zabrać, jak się skomunikować z serwerem poli?

**Comment by mik-laj** [comment]
Hej. 
My aktualnie rozpoczeliśmy pracę nad wersja webową. 
https://github.com/KlubJagiellonski/pola-web

Na razie chcemy dać możliwość wprowadzania kodu kreskowego w Web UI, ale w dalszej perspektywie również wyszukiwanie po nazwach.

Z wyrazami szacunku,

**Comment by mik-laj** [comment]
Done. https://www.pola-app.pl/
